# Generated by Django 5.2.7 on 2026-03-24 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('attendanceid', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'attendance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('enrollment_id', models.AutoField(primary_key=True, serialize=False)),
                ('enrollment_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'enrollments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('guardian_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'guardians',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Outcome',
            fields=[
                ('outcomeid', models.IntegerField(primary_key=True, serialize=False)),
                ('gradewhenenrolled', models.CharField(blank=True, max_length=20, null=True)),
                ('dateenrolled', models.DateField(blank=True, null=True)),
                ('dateexited', models.DateField(blank=True, null=True)),
                ('graduationdate', models.CharField(blank=True, max_length=10, null=True)),
                ('acceptedcollege', models.TextField(blank=True, null=True)),
                ('attendedcollege', models.TextField(blank=True, null=True)),
                ('collegename', models.CharField(blank=True, max_length=100, null=True)),
                ('majorminor', models.CharField(blank=True, max_length=100, null=True)),
                ('scholarship', models.TextField(blank=True, null=True)),
                ('stemcareer', models.TextField(blank=True, null=True)),
                ('careerfield', models.CharField(blank=True, max_length=100, null=True)),
                ('totaldayspresent', models.IntegerField(blank=True, null=True)),
                ('totaldaysabsent', models.IntegerField(blank=True, null=True)),
                ('totaldaysunknown', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'outcomes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('program_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'programs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProgramStaff',
            fields=[
                ('assignmentid', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'program_staff',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProgramYear',
            fields=[
                ('program_year_id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'program_years',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('schoolid', models.AutoField(db_column='schoolid', primary_key=True, serialize=False)),
                ('school', models.CharField(db_column='school', max_length=100)),
            ],
            options={
                'db_table': 'schools',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('sessionid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('sessiondate', models.DateField()),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'sessions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('studentid', models.CharField(db_column='studentid', max_length=6, primary_key=True, serialize=False)),
                ('firstname', models.CharField(blank=True, db_column='firstname', max_length=50, null=True)),
                ('lastname', models.CharField(blank=True, db_column='lastname', max_length=50, null=True)),
                ('grade', models.CharField(blank=True, db_column='grade', max_length=20, null=True)),
                ('steminterest', models.CharField(blank=True, db_column='steminterest', max_length=20, null=True)),
                ('enrollmentdate', models.DateField(blank=True, db_column='enrollmentdate', null=True)),
                ('studentphone', models.CharField(blank=True, db_column='studentphone', max_length=20, null=True)),
                ('guardianname', models.CharField(blank=True, db_column='guardianname', max_length=100, null=True)),
                ('guardianphone', models.CharField(blank=True, db_column='guardianphone', max_length=20, null=True)),
                ('email', models.CharField(blank=True, db_column='email', max_length=100, null=True)),
            ],
            options={
                'db_table': 'students',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.AutoField(db_column='userid', primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, db_column='username', max_length=50, null=True, unique=True)),
                ('password', models.CharField(blank=True, db_column='password', max_length=255, null=True)),
                ('fullname', models.CharField(blank=True, db_column='fullname', max_length=100, null=True)),
                ('email', models.CharField(blank=True, db_column='email', max_length=100, null=True)),
                ('createdat', models.DateTimeField(blank=True, db_column='createdat', null=True)),
                ('role', models.CharField(blank=True, db_column='role', max_length=20, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('activation_token', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Need',
            fields=[
                ('needid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('amount_needed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('urgency', models.CharField(default='Medium', max_length=20)),
            ],
            options={
                'db_table': 'needs',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('survey_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('program_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.programyear')),
            ],
            options={
                'db_table': 'surveys',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('response_id', models.AutoField(primary_key=True, serialize=False)),
                ('responses_json', models.JSONField(default=dict)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('responder_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.survey')),
            ],
            options={
                'db_table': 'survey_responses',
                'managed': True,
            },
        ),
    ]
