# Generated by Django 5.2.7 on 2026-03-19 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('attendanceid', models.AutoField(db_column='attendanceid', primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, db_column='status', max_length=20, null=True)),
                ('notes', models.TextField(blank=True, db_column='notes', null=True)),
            ],
            options={
                'verbose_name': 'Attendance Record',
                'verbose_name_plural': 'Attendance Records',
                'db_table': 'attendance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('enrollment_id', models.AutoField(db_column='enrollment_id', primary_key=True, serialize=False)),
                ('enrollment_date', models.DateField(auto_now_add=True, db_column='enrollment_date')),
                ('status', models.CharField(db_column='status', default='Active', max_length=20)),
            ],
            options={
                'verbose_name': 'Enrollment',
                'verbose_name_plural': 'Enrollments',
                'db_table': 'enrollements',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('guardian_id', models.AutoField(db_column='guardian_id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=150)),
                ('phone', models.CharField(blank=True, db_column='phone', max_length=20, null=True)),
                ('email', models.CharField(blank=True, db_column='email', max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Guardian',
                'verbose_name_plural': 'Guardians',
                'db_table': 'guardians',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Outcome',
            fields=[
                ('outcomeid', models.AutoField(db_column='outcomeid', primary_key=True, serialize=False)),
                ('gradewhenenrolled', models.CharField(blank=True, db_column='gradewhenenrolled', max_length=20, null=True)),
                ('dateenrolled', models.DateField(blank=True, db_column='dateenrolled', null=True)),
                ('dateexited', models.DateField(blank=True, db_column='dateexited', null=True)),
                ('graduationdate', models.DateField(blank=True, db_column='graduationdate', null=True)),
                ('acceptedcollege', models.CharField(blank=True, db_column='acceptedcollege', max_length=100, null=True)),
                ('attendedcollege', models.CharField(blank=True, db_column='attendedcollege', max_length=100, null=True)),
                ('collegename', models.CharField(blank=True, db_column='collegename', max_length=100, null=True)),
                ('majorminor', models.CharField(blank=True, db_column='majorminor', max_length=100, null=True)),
                ('scholarship', models.CharField(blank=True, db_column='scholarship', max_length=100, null=True)),
                ('stemcareer', models.CharField(blank=True, db_column='stemcareer', max_length=100, null=True)),
                ('careerfield', models.CharField(blank=True, db_column='careerfield', max_length=100, null=True)),
                ('totaldayspresent', models.IntegerField(blank=True, db_column='totaldayspresent', null=True)),
                ('totaldaysabsent', models.IntegerField(blank=True, db_column='totaldaysabsent', null=True)),
                ('totaldaysunknown', models.IntegerField(blank=True, db_column='totaldaysunknown', null=True)),
            ],
            options={
                'verbose_name': 'Outcome',
                'verbose_name_plural': 'Outcomes',
                'db_table': 'outcomes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('program_id', models.AutoField(db_column='program_id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=150)),
                ('description', models.TextField(blank=True, db_column='description', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', null=True)),
            ],
            options={
                'verbose_name': 'Program',
                'verbose_name_plural': 'Programs',
                'db_table': 'programs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProgramStaff',
            fields=[
                ('assignmentid', models.AutoField(db_column='assignmentid', primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Program Staff Assignment',
                'verbose_name_plural': 'Program Staff Assignments',
                'db_table': 'program_staff',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProgramYear',
            fields=[
                ('program_year_id', models.AutoField(db_column='program_year_id', primary_key=True, serialize=False)),
                ('year', models.CharField(db_column='year', max_length=20)),
                ('start_date', models.DateField(blank=True, db_column='start_date', null=True)),
                ('end_date', models.DateField(blank=True, db_column='end_date', null=True)),
            ],
            options={
                'verbose_name': 'Program Year',
                'verbose_name_plural': 'Program Years',
                'db_table': 'program_years',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('schoolid', models.AutoField(db_column='schoolid', primary_key=True, serialize=False)),
                ('school', models.CharField(blank=True, db_column='school', max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'School',
                'verbose_name_plural': 'Schools',
                'db_table': 'schools',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('sessionid', models.AutoField(db_column='sessionid', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='title', max_length=100)),
                ('sessiondate', models.DateField(db_column='sessiondate')),
                ('description', models.CharField(blank=True, db_column='description', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Session',
                'verbose_name_plural': 'Sessions',
                'db_table': 'sessions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('studentid', models.CharField(db_column='studentid', max_length=6, primary_key=True, serialize=False)),
                ('firstname', models.CharField(db_column='firstname', max_length=50)),
                ('lastname', models.CharField(db_column='lastname', max_length=50)),
                ('grade', models.CharField(blank=True, db_column='grade', max_length=20, null=True)),
                ('studentphone', models.CharField(blank=True, db_column='studentphone', max_length=20, null=True)),
                ('guardianname', models.CharField(blank=True, db_column='guardianname', max_length=100, null=True)),
                ('guardianphone', models.CharField(blank=True, db_column='guardianphone', max_length=20, null=True)),
                ('email', models.CharField(blank=True, db_column='email', max_length=100, null=True)),
                ('steminterest', models.CharField(blank=True, db_column='steminterest', max_length=20, null=True)),
                ('enrollmentdate', models.DateField(blank=True, db_column='enrollementdate', null=True)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'db_table': 'students',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.AutoField(db_column='userid', primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, db_column='username', max_length=50, null=True, unique=True)),
                ('password', models.CharField(db_column='password', max_length=255)),
                ('fullname', models.CharField(blank=True, db_column='fullname', max_length=100, null=True)),
                ('email', models.CharField(blank=True, db_column='email', max_length=100, null=True)),
                ('createdat', models.DateTimeField(blank=True, db_column='createdat', null=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('staff', 'Staff'), ('parent', 'Parent/Guardian'), ('student', 'Student')], db_column='role', default='staff', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('activation_token', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Need',
            fields=[
                ('needid', models.AutoField(db_column='needid', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='title', max_length=100)),
                ('description', models.TextField(blank=True, db_column='description', null=True)),
                ('amount_needed', models.DecimalField(db_column='amount_needed', decimal_places=2, max_digits=10)),
                ('current_amount', models.DecimalField(db_column='current_amount', decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('urgency', models.CharField(db_column='urgency', default='Medium', max_length=20)),
            ],
            options={
                'verbose_name': 'Need',
                'verbose_name_plural': 'Needs',
                'db_table': 'needs',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('survey_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('target_audience', models.CharField(choices=[('Parent', 'Parent'), ('Staff', 'Staff'), ('Student', 'Student')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('program_year', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='core.programyear')),
            ],
            options={
                'verbose_name': 'Survey',
                'verbose_name_plural': 'Surveys',
                'db_table': 'surveys',
            },
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('response_id', models.AutoField(primary_key=True, serialize=False)),
                ('response_data', models.JSONField(default=dict)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('responder_user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.user')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='core.survey')),
            ],
            options={
                'verbose_name': 'Survey Response',
                'verbose_name_plural': 'Survey Responses',
                'db_table': 'survey_responses',
            },
        ),
    ]
