# Generated by Django 5.2.7 on 2026-01-28 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('attendanceid', models.AutoField(db_column='attendanceid', primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, db_column='status', max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Attendance Record',
                'verbose_name_plural': 'Attendance Records',
                'db_table': 'attendance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Outcome',
            fields=[
                ('outcomeid', models.AutoField(db_column='outcomeid', primary_key=True, serialize=False)),
                ('graduationyear', models.IntegerField(blank=True, db_column='graduationyear', null=True)),
                ('collegename', models.CharField(blank=True, db_column='collegename', max_length=100, null=True)),
                ('major', models.CharField(blank=True, db_column='major', max_length=100, null=True)),
                ('careerpath', models.CharField(blank=True, db_column='careerpath', max_length=100, null=True)),
                ('isstem', models.BooleanField(blank=True, db_column='isstem', null=True)),
            ],
            options={
                'verbose_name': 'Outcome',
                'verbose_name_plural': 'Outcomes',
                'db_table': 'outcomes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('schoolid', models.AutoField(db_column='schoolid', primary_key=True, serialize=False)),
                ('school', models.CharField(blank=True, db_column='school', max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'School',
                'verbose_name_plural': 'Schools',
                'db_table': 'schools',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('studentid', models.CharField(db_column='studentid', max_length=6, primary_key=True, serialize=False)),
                ('firstname', models.CharField(db_column='firstname', max_length=50)),
                ('lastname', models.CharField(db_column='lastname', max_length=50)),
                ('grade', models.CharField(blank=True, db_column='grade', max_length=20, null=True)),
                ('studentphone', models.CharField(blank=True, db_column='studentphone', max_length=20, null=True)),
                ('guardianname', models.CharField(blank=True, db_column='guardianname', max_length=100, null=True)),
                ('guardianphone', models.CharField(blank=True, db_column='guardianphone', max_length=20, null=True)),
                ('email', models.CharField(blank=True, db_column='email', max_length=100, null=True)),
                ('steminterest', models.CharField(blank=True, db_column='steminterest', max_length=20, null=True)),
                ('enrollmentdate', models.DateField(blank=True, db_column='enrollmentdate', null=True)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'db_table': 'students',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.AutoField(db_column='userid', primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, db_column='username', max_length=50, null=True, unique=True)),
                ('password', models.CharField(db_column='password', max_length=255)),
                ('fullname', models.CharField(blank=True, db_column='fullname', max_length=100, null=True)),
                ('email', models.CharField(blank=True, db_column='email', max_length=100, null=True)),
                ('createdat', models.DateTimeField(blank=True, db_column='createdat', null=True)),
                ('role', models.CharField(db_column='role', default='teacher', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('activation_token', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('sessionid', models.AutoField(db_column='sessionid', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='title', max_length=100)),
                ('sessiondate', models.DateField(db_column='sessiondate')),
                ('description', models.CharField(blank=True, db_column='description', max_length=255, null=True)),
                ('schoolid', models.ForeignKey(blank=True, db_column='schoolid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.school')),
            ],
            options={
                'verbose_name': 'Session',
                'verbose_name_plural': 'Sessions',
                'db_table': 'sessions',
                'managed': True,
            },
        ),
    ]
