# Generated by Django 5.2.7 on 2026-03-18 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Need',
            fields=[
                ('needid', models.AutoField(db_column='needid', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='title', max_length=100)),
                ('description', models.TextField(blank=True, db_column='description', null=True)),
                ('amount_needed', models.DecimalField(db_column='amount_needed', decimal_places=2, max_digits=10)),
                ('current_amount', models.DecimalField(db_column='current_amount', decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('urgency', models.CharField(db_column='urgency', default='Medium', max_length=20)),
            ],
            options={
                'verbose_name': 'Need',
                'verbose_name_plural': 'Needs',
                'db_table': 'needs',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('programid', models.AutoField(db_column='programid', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=150)),
                ('description', models.TextField(blank=True, db_column='description', null=True)),
            ],
            options={
                'verbose_name': 'Program',
                'verbose_name_plural': 'Programs',
                'db_table': 'programs',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProgramYear',
            fields=[
                ('programyearid', models.AutoField(db_column='programyearid', primary_key=True, serialize=False)),
                ('year', models.CharField(db_column='year', max_length=20)),
                ('start_date', models.DateField(blank=True, db_column='start_date', null=True)),
                ('end_date', models.DateField(blank=True, db_column='end_date', null=True)),
                ('program', models.ForeignKey(db_column='programid', on_delete=django.db.models.deletion.CASCADE, to='core.program')),
            ],
            options={
                'verbose_name': 'Program Year',
                'verbose_name_plural': 'Program Years',
                'db_table': 'program_years',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProgramStaff',
            fields=[
                ('assignmentid', models.AutoField(db_column='assignmentid', primary_key=True, serialize=False)),
                ('user', models.ForeignKey(db_column='userid', on_delete=django.db.models.deletion.CASCADE, to='core.user')),
                ('program_year', models.ForeignKey(db_column='programyearid', on_delete=django.db.models.deletion.CASCADE, to='core.programyear')),
            ],
            options={
                'verbose_name': 'Program Staff Assignment',
                'verbose_name_plural': 'Program Staff Assignments',
                'db_table': 'program_staff',
                'managed': True,
                'unique_together': {('program_year', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('enrollmentid', models.AutoField(db_column='enrollmentid', primary_key=True, serialize=False)),
                ('enrolled_date', models.DateField(auto_now_add=True, db_column='enrolled_date')),
                ('status', models.CharField(db_column='status', default='Active', max_length=20)),
                ('student', models.ForeignKey(db_column='studentid', on_delete=django.db.models.deletion.CASCADE, to='core.student')),
                ('program_year', models.ForeignKey(db_column='programyearid', on_delete=django.db.models.deletion.CASCADE, to='core.programyear')),
            ],
            options={
                'verbose_name': 'Enrollment',
                'verbose_name_plural': 'Enrollments',
                'db_table': 'enrollments',
                'managed': True,
                'unique_together': {('student', 'program_year')},
            },
        ),
    ]
